name: CI

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  quality-checks:
    uses: ./.github/workflows/reusable-build.yml
    with:
      node-version: 22
    secrets:
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
      CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      UPLOADTHING_TOKEN: ${{ secrets.UPLOADTHING_TOKEN }}
